branches:
  only:
    - master
language: node_js
node_js:
  - 8
env:
  global:
    - COVERAGE_OPTION='./node_modules/.bin/nyc'
script: npm run coverage
after_scrypt: bash <(curl -s https://codecov.io/bash)
