branches:
  only:
    - master
language: node_js
node_js: '10'
env:
  global:
    - COVERAGE_OPTION='./node_modules/.bin/nyc'
script: npm run coverage
after_success: bash <(curl -s https://codecov.io/bash)
