name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  check-lint:
    name: Lint
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
  test:
    strategy:
      matrix:
        node: [ '14', '16', '18', '19' ]
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      COVERAGE_OPTION: ./node_modules/.bin/nyc
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - run: npm run coverage
      - run: bash <(curl -s https://codecov.io/bash)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
